name: "Maven Flow Merge"
description: "Merges chenges between branchs. Uses a special merge driver for changelogs."

inputs:
  changelog-file:
    default: "**/CHANGELOG.md"
    required: false
    type: string
  pom-file:
    default: "**/pom.xml"
    required: false
    type: string
  source-branch:
    required: true
    type: string
  target-branch:
    required: true
    type: string

runs:
  using: "composite"
  steps:

  - name: Configure pom merge driver
    shell: bash
    run: |
      git config merge.pom.driver "${{ github.action_path }}/pom-merge-driver.sh %A %O %B"
      if [ ! -f ".gitattributes" ]; then
        echo "${{ inputs.pom-file }} merge=pom" > ".gitattributes"
      else
        echo "${{ inputs.pom-file }} merge=pom" >> ".gitattributes"
      fi

  - name: Configure changelog merge driver
    shell: bash
    run: |
      git config merge.changelog.driver "java -jar ${{ github.action_path }}/changelog-merge-driver.jar %A %O %B"
      if [ ! -f ".gitattributes" ]; then
        echo "${{ inputs.changelog-file }} merge=changelog" > ".gitattributes"
      else
        echo "${{ inputs.changelog-file }} merge=changelog" >> ".gitattributes"
      fi

  - name: Perform Merge
    shell: bash
    run: |
      echo "Merging from branch ${{ inputs.source-branch }} to branch: ${{ inputs.target-branch }}"
      git config --local user.email "github-actions[bot]@users.noreply.github.com"
      git config --local user.name "github-actions[bot]"
      git checkout ${{ inputs.target-branch }}
      git merge --no-ff --no-edit ${{ inputs.source-branch }}
      git push origin ${{ inputs.target-branch }}
