name: Run Tests

on:
  push:
    branches:
      - main
      - develop
    tags:
      - v1
  workflow_dispatch:

jobs:

  run tests:
    runs-on: ubuntu-latest
    steps:
    - run: |
      gh workflow run mf-merge-from-develop.yml --repo maven-flow/merge-tests --ref feature/add-cranberry -f action-ref=${{ github.ref_name }}
      gh workflow run mf-merge-from-release.yml --repo maven-flow/merge-tests --ref develop -f action-ref=${{ github.ref_name }} -f release-branch=origin/release/1.0
